encrypt.settings:
  type: mapping
  label: Settings
  mapping:
    encrypt_test_trigger_unmet_deps:
      type: boolean
    encrypt_default_config:
      type: 'NULL'
    encrypt_encryption_method:
      type: string
    encrypt_key_provider:
      type: string
    encrypt_drupal_variable_key:
      type: 'NULL'
    encrypt_default_method:
      type: 'NULL'
    encrypt_secure_key_path:
      type: 'NULL'
